[versions]
graphql = "8.8.1"
kermit = "2.0.4"

[libraries]
graphql-ktor = { module = "com.expediagroup:graphql-kotlin-ktor-client", version.ref = "graphql" }
graphql-serialization = { module = "com.expediagroup:graphql-kotlin-client-serialization", version.ref = "graphql" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

[plugins]
graphql = { id = "com.expediagroup.graphql", version.ref = "graphql" }